name: Verify Pull Request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests on node ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:all

